import type { Metadata } from "next";
// import { Providers } from "./providers";
import {
  Geist,
  Geist_Mono,
  Radio_Canada_Big,
  Source_Serif_4,
  Work_Sans,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// impor";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} antialiased bg-[242535]`}>
        {/* <Navbar /> */}
      {children}
      </body>
    </html>
  );
}
